steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/unique-epigram-458904-p8/pdf-parser-api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/unique-epigram-458904-p8/pdf-parser-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - pdf-parser-api
      - --image
      - gcr.io/unique-epigram-458904-p8/pdf-parser-api
      - --platform
      - managed
      - --region
      - us-central1
      - --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY
